######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 18:31:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cmdline.h consoleout.h maingui.h options.h
SOURCES += cmdline.cpp consoleout.cpp main.cpp maingui.cpp options.cpp
